[package]
name = "mc-server"
version = "0.1.0"
authors = ["Jaden Buchan <me@jaden.bio>"]
edition = "2018"

[dependencies]
server = { path = "./server" }

event-bus = "0.1"
log = "0.4"
anyhow = "1.0"
bytes = "0.5"
async-trait = "0.1"
tokio = { version = "0.2", features = ["full"] }
flume = "0.7"